footnoteReturnLinkContents = "↩"
title = "BernCarney"
googleAnalytics =""

# Code higlighting settings
pygmentsCodefences = true

[params]
  author = "Bern"
  description = "Description here..."
  keywords = "something, somethingElse, againElse"

[permalinks]
  posts = "/:year/:month/:title/"
