footnoteReturnLinkContents = "↩"
title = "Bern Carney"
googleAnalytics =""

# Code higlighting settings
pygmentsCodefences = true

[params]
  AuthorName = "Bern"

[permalinks]
  posts = "/:year/:month/:title/"
